version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
#    volumes:
#      - ./backend/:/backend/
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "cd backend &&
      alembic upgrade heads &&
      cd .. &&
             uvicorn backend.app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000"
#    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
  db:
    image: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 5

